DROP TABLE MyUser;

CREATE TABLE MyUser(
	/*ID INT IDENTITY(111,3) PRIMARY KEY,*/
	myUser VARCHAR(256),
	myEmail VARCHAR(256),
	myAddress VARCHAR(256),
	phone VARCHAR(15),
	city VARCHAR(60),
	province VARCHAR(60),
	country VARCHAR(256)
);
