//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIdentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyUser
    {
        public int ID { get; set; }
        public string myUser1 { get; set; }
        public string myEmail { get; set; }
        public string myAddress { get; set; }
        public string phone { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
    }
}
